name: branch_name_lint
description: A special tool to improve work with branches in teams
version: 1.0.0
repository: https://github.com/ScerIO/packages.dart
homepage: https://github.com/ScerIO/packages.dart/tree/master/packages/branch_name_lint

environment:
  sdk: ^3.6.0

dependencies:
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  husky: ^0.1.7
  lints: ^5.0.0
  test: ^1.24.0
